# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        name: isort-local
        entry: isort
        language: python
        types: [python]
    -   id: black
        name: black-local
        entry: black
        language: python
        types: [python]
    -   id: pylint
        name: pylint-local
        entry: pylint --output-format=colorized
        language: python
        types: [python]
    -   id: flake8
        name: flake8-local
        entry: flake8
        language: python
        types: [python]
    -   id: pytest
        name: pytest-local
        entry: pytest -v
        language: python
        types: [python]

-   repo: https://github.com/jorisroovers/gitlint
    rev: '1a0ed8d03ac002f74f1b33706d509dcb4425ab4d'
    hooks:
    -   id: gitlint
